-- Farm Adventure v15 Supabase schema
-- Supabase SQL Editor에서 아래 SQL을 실행하세요.

create table if not exists mission_responses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  data jsonb not null
);

create table if not exists quiz_responses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  data jsonb not null
);

create table if not exists generated_mission_sets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  data jsonb not null
);
